# Generated by Django 3.1 on 2020-08-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstChoice', models.CharField(max_length=10)),
                ('secondChoice', models.CharField(max_length=10)),
                ('thirdChoice', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=100)),
                ('postID', models.CharField(max_length=20)),
            ],
        ),
    ]
