# Generated by Django 3.1 on 2020-08-07 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_choice', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
